version: 2.1

orbs:
  aws-s3: circleci/aws-s3@4
  browser-tools: circleci/browser-tools@1
  codecov: codecov/codecov@3.2.5

executors:
  node:
    docker:
      - image: cimg/node:18.17.1-browsers
  python:
    docker:
      - image: cimg/python:3.6

#############################################################
# Define workflows
#############################################################
workflows:
  pipeline:
    jobs:
      - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - deploy:
          context: AWS
          requires:
            - unit_tests
            - build
            - lint
          filters:
            branches:
              only:
                - main

#############################################################
# Define jobs
#############################################################
jobs:
  install_dependencies:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  lint:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm run lint

  unit_tests:
    working_directory: ~/app
    executor: node
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: 
          environment:
            # JUNIT_REPORT_PATH: ./junit/
            # JUNIT_REPORT_NAME: test-results.xml
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage
          when: always      
      - codecov/upload
      - store_test_results:
          path: /home/circleci/app/coverage/feed-me-web/junit

  build:
    working_directory: ~/app
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm run build -- --configuration production
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - store_artifacts:
          path: /home/circleci/app/dist/feed-me-web

  deploy:
    executor: python
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./dist/feed-me-web
          to: "s3://feed-me.io"
