version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  coveralls: coveralls/coveralls@1.0.6

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - build:
          requires:
            - lint
            - unit_tests
      - deploy:
          context: AWS
          requires:
            - build
          filters:
            branches:
              only:
                - main

#############################################################
# Define jobs
#############################################################
jobs:
  install_dependencies:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  lint:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm run lint

  unit_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm run test -- --watch=false --code-coverage
      - coveralls/upload:
          path_to_lcov: ./coverage/feed-me-web/lcov.info

  e2e_tests:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm run e2e

  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run: npm run build -- --prod
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: ./dist/feed-me-web
          to: "s3://feed-me.io"
